# Generated by Django 5.2.17 on 2026-09-02 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0002_remove_sector_unique_sector_por_area_area_created_at_and_more'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('tipo_movimiento', models.CharField(choices=[('ALTA', 'Alta'), ('ASIGNACION', 'Asignación'), ('TRASLADO', 'Traslado'), ('DESASIGNACION', 'Desasignación'), ('REPARACION', 'Ingreso a reparación'), ('RETORNO_REPARACION', 'Retorno de reparación'), ('RESERVA', 'Reserva'), ('DISPONIBLE', 'Disponible'), ('BAJA', 'Baja')], db_index=True, max_length=30, verbose_name='tipo de movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha')),
                ('estado_anterior', models.CharField(blank=True, choices=[('EN_USO', 'En uso'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado anterior')),
                ('estado_resultante', models.CharField(blank=True, choices=[('EN_USO', 'En uso'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado resultante')),
                ('motivo', models.CharField(blank=True, max_length=250, verbose_name='motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.activo', verbose_name='activo')),
                ('equipo_trabajo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos_destino', to='inventario.equipotrabajo', verbose_name='equipo de trabajo de destino')),
                ('equipo_trabajo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos_origen', to='inventario.equipotrabajo', verbose_name='equipo de trabajo de origen')),
                ('sector_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos_destino', to='estructura.sector', verbose_name='sector de destino')),
                ('sector_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos_origen', to='estructura.sector', verbose_name='sector de origen')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Movimiento de activo',
                'verbose_name_plural': 'Movimientos de activos',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['activo', 'fecha'], name='idx_mov_activo_fecha'), models.Index(fields=['tipo_movimiento'], name='idx_mov_activo_tipo')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('tipo_movimiento', models.CharField(choices=[('ALTA', 'Alta'), ('INSTALACION', 'Instalación'), ('RETIRO', 'Retiro'), ('REEMPLAZO', 'Reemplazo'), ('REPARACION', 'Ingreso a reparación'), ('RETORNO_REPARACION', 'Retorno de reparación'), ('RESERVA', 'Reserva'), ('DISPONIBLE', 'Disponible'), ('BAJA', 'Baja')], db_index=True, max_length=30, verbose_name='tipo de movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha')),
                ('estado_anterior', models.CharField(blank=True, choices=[('INSTALADO', 'Instalado'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado anterior')),
                ('estado_resultante', models.CharField(blank=True, choices=[('INSTALADO', 'Instalado'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado resultante')),
                ('motivo', models.CharField(blank=True, max_length=250, verbose_name='motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_componentes_destino', to='inventario.activo', verbose_name='activo de destino')),
                ('activo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_componentes_origen', to='inventario.activo', verbose_name='activo de origen')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.componente', verbose_name='componente')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Movimiento de componente',
                'verbose_name_plural': 'Movimientos de componentes',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['componente', 'fecha'], name='idx_mov_comp_fecha'), models.Index(fields=['tipo_movimiento'], name='idx_mov_comp_tipo')],
            },
        ),
    ]
