# Generated by Django 5.2.17 on 2026-09-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocomponente',
            name='activo_destino',
        ),
        migrations.RemoveField(
            model_name='movimientocomponente',
            name='activo_origen',
        ),
        migrations.RemoveField(
            model_name='movimientocomponente',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='movimientocomponente',
            name='user_deleted',
        ),
        migrations.RemoveField(
            model_name='movimientocomponente',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='movimientocomponente',
            name='user_updated',
        ),
        migrations.DeleteModel(
            name='MovimientoActivo',
        ),
        migrations.DeleteModel(
            name='MovimientoComponente',
        ),
    ]
