# Generated by Django 5.2.17 on 2026-09-03 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0002_remove_sector_unique_sector_por_area_area_created_at_and_more'),
        ('inventario', '0005_sistemaoperativo_alter_activo_sistema_operativo_and_more'),
        ('operaciones', '0002_remove_movimientocomponente_activo_destino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('tipo_movimiento', models.CharField(choices=[('ASIGNACION', 'Asignación a equipo'), ('TRASLADO', 'Traslado'), ('RETIRO_STOCK', 'Retiro a stock'), ('SALIDA_STOCK', 'Salida de stock'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ENVIO_REPARACION', 'Envío a reparación'), ('RETORNO_REPARACION', 'Retorno de reparación'), ('BAJA', 'Baja definitiva')], db_index=True, max_length=30, verbose_name='tipo de movimiento')),
                ('ubicacion_origen', models.CharField(choices=[('EQUIPO_TRABAJO', 'Equipo de trabajo'), ('STOCK', 'Stock de Sistemas'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja definitiva')], max_length=20, verbose_name='ubicación origen')),
                ('ubicacion_destino', models.CharField(choices=[('EQUIPO_TRABAJO', 'Equipo de trabajo'), ('STOCK', 'Stock de Sistemas'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja definitiva')], max_length=20, verbose_name='ubicación destino')),
                ('estado_anterior', models.CharField(choices=[('EN_USO', 'En uso'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('EN_USO', 'En uso'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado nuevo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.activo', verbose_name='activo')),
                ('equipo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos_entrada', to='inventario.equipotrabajo', verbose_name='equipo destino')),
                ('equipo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos_salida', to='inventario.equipotrabajo', verbose_name='equipo origen')),
                ('sector_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estructura.sector', verbose_name='sector destino')),
                ('sector_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estructura.sector', verbose_name='sector origen')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Movimiento de activo',
                'verbose_name_plural': 'Movimientos de activos',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['activo', 'created_at'], name='idx_mov_act_fecha'), models.Index(fields=['tipo_movimiento'], name='idx_mov_act_tipo')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('tipo_movimiento', models.CharField(choices=[('INSTALACION', 'Instalación en activo'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('RETIRO_STOCK', 'Retiro a stock'), ('ENVIO_REPARACION', 'Envío a reparación'), ('RETORNO_REPARACION', 'Retorno de reparación'), ('BAJA', 'Baja definitiva')], db_index=True, max_length=30, verbose_name='tipo de movimiento')),
                ('ubicacion_origen', models.CharField(choices=[('ACTIVO', 'Instalado en activo'), ('STOCK', 'Stock de Sistemas'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja definitiva')], max_length=20, verbose_name='ubicación origen')),
                ('ubicacion_destino', models.CharField(choices=[('ACTIVO', 'Instalado en activo'), ('STOCK', 'Stock de Sistemas'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja definitiva')], max_length=20, verbose_name='ubicación destino')),
                ('estado_anterior', models.CharField(choices=[('INSTALADO', 'Instalado'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('INSTALADO', 'Instalado'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], max_length=20, verbose_name='estado nuevo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_componentes_entrada', to='inventario.activo', verbose_name='activo destino')),
                ('activo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_componentes_salida', to='inventario.activo', verbose_name='activo origen')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.componente', verbose_name='componente')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Movimiento de componente',
                'verbose_name_plural': 'Movimientos de componentes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['componente', 'created_at'], name='idx_mov_comp_fecha'), models.Index(fields=['tipo_movimiento'], name='idx_mov_comp_tipo')],
            },
        ),
    ]
