# Generated by Django 5.2.17 on 2026-09-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoactivo',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ASIGNACION', 'Asignación a equipo'), ('TRASLADO', 'Traslado'), ('RETIRO_STOCK', 'Retiro a stock'), ('SALIDA_STOCK', 'Salida de stock'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ACTUALIZACION_CONFIGURACION', 'Actualización de configuración'), ('ENVIO_REPARACION', 'Envío a reparación'), ('RETORNO_REPARACION', 'Retorno de reparación'), ('BAJA', 'Baja definitiva')], db_index=True, max_length=30, verbose_name='tipo de movimiento'),
        ),
    ]
