# Generated by Django 5.2.17 on 2026-09-02 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0002_remove_sector_unique_sector_por_area_area_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(help_text='Ej.: Equipo de Facturación Nacionales.', max_length=150, verbose_name='nombre')),
                ('uso_actual', models.CharField(blank=True, help_text='Referencia libre. Ej.: Melisa Rufino.', max_length=150, verbose_name='uso actual')),
                ('foto', models.ImageField(blank=True, help_text='Una única foto identificatoria del equipo de trabajo.', null=True, upload_to='equipos_trabajo/', verbose_name='foto')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=20, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_trabajo', to='estructura.sector', verbose_name='sector')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Equipo de trabajo',
                'verbose_name_plural': 'Equipos de trabajo',
                'ordering': ['sector__area__nombre', 'sector__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de activo',
                'verbose_name_plural': 'Tipos de activo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('codigo_inventario', models.CharField(help_text='Ej.: CPU-0034, MON-0041, TEC-0078.', max_length=50, verbose_name='código de inventario')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=150, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=150, verbose_name='número de serie')),
                ('hostname', models.CharField(blank=True, help_text='Principalmente para CPU, notebook o servidor.', max_length=100, verbose_name='hostname')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('estado', models.CharField(choices=[('EN_USO', 'En uso'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], db_index=True, default='EN_USO', max_length=20, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='estructura.sector', verbose_name='sector')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('equipo_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventario.equipotrabajo', verbose_name='equipo de trabajo')),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.tipoactivo', verbose_name='tipo de activo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['codigo_inventario'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de componente',
                'verbose_name_plural': 'Tipos de componente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=150, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=150, verbose_name='número de serie')),
                ('capacidad', models.CharField(blank=True, help_text='Ej.: 8 GB, 500 GB, 1 TB.', max_length=100, verbose_name='capacidad')),
                ('estado', models.CharField(choices=[('INSTALADO', 'Instalado'), ('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_REPARACION', 'En reparación'), ('DEFECTUOSO', 'Defectuoso'), ('BAJA', 'Dado de baja')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='estado')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.ForeignKey(blank=True, help_text='Activo en el que está instalado actualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='inventario.activo', verbose_name='activo instalado')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('tipo_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='inventario.tipocomponente', verbose_name='tipo de componente')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['tipo_componente__nombre', 'marca', 'modelo'],
            },
        ),
        migrations.AddIndex(
            model_name='equipotrabajo',
            index=models.Index(fields=['estado'], name='idx_equipo_estado'),
        ),
        migrations.AddIndex(
            model_name='equipotrabajo',
            index=models.Index(fields=['sector'], name='idx_equipo_sector'),
        ),
        migrations.AddConstraint(
            model_name='equipotrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sector', 'nombre'), name='unique_equipo_trabajo_activo_por_sector'),
        ),
        migrations.AddConstraint(
            model_name='tipoactivo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nombre',), name='unique_tipo_activo_no_eliminado'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['codigo_inventario'], name='idx_activo_codigo'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['hostname'], name='idx_activo_hostname'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['estado'], name='idx_activo_estado'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['sector'], name='idx_activo_sector'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['equipo_trabajo'], name='idx_activo_equipo'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('codigo_inventario',), name='unique_codigo_activo_no_eliminado'),
        ),
        migrations.AddConstraint(
            model_name='tipocomponente',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nombre',), name='unique_tipo_componente_no_eliminado'),
        ),
        migrations.AddIndex(
            model_name='componente',
            index=models.Index(fields=['estado'], name='idx_componente_estado'),
        ),
        migrations.AddIndex(
            model_name='componente',
            index=models.Index(fields=['activo'], name='idx_componente_activo'),
        ),
        migrations.AddIndex(
            model_name='componente',
            index=models.Index(fields=['tipo_componente'], name='idx_componente_tipo'),
        ),
    ]
