# Generated by Django 5.2.17 on 2026-09-02 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactivo',
            name='prefijo',
            field=models.CharField(help_text='Prefijo para generar el código de inventario. Ej.: CPU, MON, TEC.', max_length=5, null=True, verbose_name='prefijo'),
        ),
        migrations.AddConstraint(
            model_name='tipoactivo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('prefijo',), name='unique_prefijo_tipo_activo_no_eliminado'),
        ),
    ]
