# Generated by Django 5.2.17 on 2026-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_tipoactivo_prefijo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='componente',
            name='capacidad_unidad',
            field=models.CharField(blank=True, choices=[('MB', 'MB'), ('GB', 'GB'), ('TB', 'TB')], help_text='Ej.: GB o TB.', max_length=5, verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='componente',
            name='capacidad_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej.: 8, 16, 256, 500, 1.', max_digits=10, null=True, verbose_name='capacidad'),
        ),
        migrations.AddField(
            model_name='tipocomponente',
            name='tipos_activo_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Tipos de activo donde este componente puede instalarse. Ej.: RAM puede utilizarse en CPU, Notebook y Servidor.', related_name='tipos_componentes_permitidos', to='inventario.tipoactivo', verbose_name='tipos de activo permitidos'),
        ),
    ]
