# Generated by Django 5.2.17 on 2026-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_componente_capacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='sistema_operativo',
            field=models.CharField(blank=True, help_text='Ej.: Windows 11 Pro, Windows Server 2022, Ubuntu 24.04.', max_length=150, verbose_name='sistema operativo'),
        ),
        migrations.AddField(
            model_name='tipoactivo',
            name='tiene_sistema_operativo',
            field=models.BooleanField(default=False, help_text='Indica si los activos de este tipo pueden tener sistema operativo. Ej.: CPU, notebook o servidor.', verbose_name='tiene sistema operativo'),
        ),
        migrations.AddField(
            model_name='tipocomponente',
            name='tiene_capacidad',
            field=models.BooleanField(default=False, help_text='Indica si este tipo de componente utiliza valor y unidad de capacidad. Ej.: RAM, SSD o HDD.', verbose_name='tiene capacidad'),
        ),
    ]
