# Generated by Django 5.2.17 on 2026-09-02 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_activo_sistema_operativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Sistema operativo',
                'verbose_name_plural': 'Sistemas operativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='activo',
            name='sistema_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventario.sistemaoperativo', verbose_name='sistema operativo'),
        ),
        migrations.AddConstraint(
            model_name='sistemaoperativo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nombre',), name='unique_sistema_operativo_no_eliminado'),
        ),
    ]
