# Generated by Django 5.2.17 on 2026-09-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_remove_sector_unique_sector_por_area_area_created_at_and_more'),
        ('inventario', '0005_sistemaoperativo_alter_activo_sistema_operativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='estructura.sector', verbose_name='sector'),
        ),
    ]
