# Generated by Django 5.2.17 on 2026-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_activo_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Dirección MAC de la interfaz de red principal.', max_length=17, null=True, verbose_name='Dirección MAC'),
        ),
        migrations.AddField(
            model_name='tipoactivo',
            name='tiene_mac',
            field=models.BooleanField(default=False, verbose_name='Tiene dirección MAC'),
        ),
    ]
